first_name_field_loc = '#firstname'
last_name_field_loc = '#lastname'
email_field_loc = '#email_address'
password_field_loc = '#password'
confirm_password_field_loc = '#password-confirmation'
button_loc = '[title="Create an Account"]'
text_create_locator = 'div[data-bind*="html: $parent.prepareMessageForHtml(message.text)"]'
first_name_error_loc = '#firstname-error'
last_name_error_loc = '#lastname-error'
email_error_loc = '#email_address-error'
password_error_loc = '#password-error'
confirm_password_error_loc = '#password-confirmation-error'
